### ISSUE TITLE
Issue with Monzo Auth

### ISSUE THREAD

**Issue by dmelliott20** [JakeMartin-ICL/ha-monzo#2]
getting this when ever i provide my email address for the monzo authentication - any ideas on what I'm doing wrong

![image](https://github.com/JakeMartin-ICL/ha-monzo/assets/13154453/1a0fc2e8-563d-447a-a340-b8b5f57161ee)

**Comment by JakeMartin-ICL** [comment]
Sorry for the delay, have you managed to set this up now? I'm not sure what this could be if you're sure you're using your Monzo email address, I haven't been able to reproduce this issue

**Comment by stuartford** [comment]
This is happening for me too. I've tried deleting the oAuth account in Monzo Developer to try to start the process again, but now the integration just keeps opening a white screen on auth.monzo.com.

**Comment by atmezferix** [comment]
@stuartford I have exactly the same issue as you and now just stuck in the auth.monzo.com whist screen (Monzo does flash up, then disappears with no response) and unable to reconfigure as unable to start the integration again.

**Comment by JakeMartin-ICL** [comment]
Would you mind sharing some details about your setups? If I could find what you have in common I might have more luck replicating the issue.

Also, could you try adding the core integration? A couple of features are still stuck in PR-purgatory, but it's worth a try

**Comment by stuartford** [comment]
What details would you like to see?

**Comment by JakeMartin-ICL** [comment]
I reckon info about your network setups and auth flow would be best. Eg.: 

- Do you use a reverse proxy, ssl, nabu cloud
- If you're reverse proxying, what're your proxy settings
- If you're using CloudFlare, have you got any extra features enabled
- What's your my.home-assistant.io pointing exactly (ssl? local?)
- What browser are you using? (maybe try with a different one too)
- Whether the core version works for you (maybe try setting it up with a new OAuth client too, to be safe)
- Anything else 'unusual' about your setup

**Comment by atmezferix** [comment]
For me I did have the HAC integration installed that I have now removed.  Trying the core versions I'm stuck in the sense I can not reapply the new credentials from Monza as all it wants to do is try to open website and re-auth.  

I'm running 2024.7.0 HA but it was the same on prior versions and I gave up, but I would like it working.

My HA is SSL and goes out through a UDM Pro with no restrictions.

Is there a way of starting the installation process again? As from the intergrations its NOT installed, but trying to install it, I've only got the option to Open Website, which just ends up on a white screen.

<img width="364" alt="Monzo Integration" src="https://github.com/JakeMartin-ICL/ha-monzo/assets/20479510/d55b56bf-f9c0-4c1d-a169-006ad8b32926">

**Comment by stuartford** [comment]
Here's my setup (in points of order):

1. Nabu cloud
2. No reverse proxy
3. No CloudFlare
4. the Nabu cloud URL as far as I can tell
5. Chrome, but the issue is the same in Edge
6. Apologies, what do you mean by the core edition? If you mean the one bundled with HA 2024.6.2 then I think that's the one I am using.
7. None to my knowledge.

If I had to guess:

1. The integration is storing/caching an invalid oAuth ID and sending it to the Monzo page
2. The Monzo page doesn't recognise it, because it's invalid, and whitescreening
3. This is poor UX from Monzo, but whatever.
4. There needs to be a way for the integration to forget whatever oAuth ID it's trying to use so we can start again.

Stuart

**Comment by JakeMartin-ICL** [comment]
> Is there a way of starting the installation process again? As from the intergrations its NOT installed, but trying to install it, I've only got the option to Open Website, which just ends up on a white screen.

You need to delete the application credentials (three dots in the top right of the devices & services screen)

**Comment by stuartford** [comment]
This has worked, thank you.

The client management feature in Monzo Developer is now broken, but that is beyond your scope! Does nothing when I submit the form, just returns to an empty list of clients.

**Comment by JakeMartin-ICL** [comment]
Yeah, I noticed my list was suspiciously empty when I went to check the details of my client. Is creating a new one not working either then?

**Comment by atmezferix** [comment]
This has worked for me, didn't even know the Application Credentials were up there !!

Reconfigured from scratch, and all working !!

Thanks, amazing integration !!

**Comment by stuartford** [comment]
Cracked it. I was ignoring the annoying Javascript pop-up in Monzo Developer that asked me to authorise it in the app. I'm completely blind to pop-ups, I click them away without even realising it.

All working now, thank you!

**Comment by JakeMartin-ICL** [comment]
Great, glad I could help! Yeah, application credentials are pretty tucked away. I might add a note to the docs about where to find them.
