### ISSUE TITLE
Not installing correctly - no initial configuration and does not show up as integration

### ISSUE THREAD

**Issue by rhysperry111** [JakeMartin-ICL/ha-monzo#3]
When I add this repo to HACS and download the integration, I get prompted to restart HA. After that, I can't find any way to configure the integration with oauth creds as it doesn't seem to show up anywhere. There are no mentions in HA logs

**Comment by rhysperry111** [comment]
I found I could fix this by going to https://my.home-assistant.io/redirect/config_flow_start/?domain=monzo

Probably best to document this in case other users experience this issue

**Comment by JakeMartin-ICL** [comment]
Hi, sorry for the delay, could you confirm if it wasn't showing up in Settings -> Devices & Services -> Add Integration?

**Comment by atmezferix** [comment]
I tried the link above, and it then says do you want to set up the Monzo integration in Home Assistant. (however I have removed my credentials and need to start the integration again, however, it's not installed in HA to reconfigure, and when you try to add it, it's just stuck on the auth page where it just goes to a blank page. So you are just stuck in a loop and unable to proceed.

**Comment by JakeMartin-ICL** [comment]
I'm going to tentatively close this issue for now (the auth loop issue was resolved in #2). If anyone else has issues with starting the config flow, please reopen or make a new issue, thanks!
