### ISSUE TITLE
Young person accounts - integration fails to setup

### ISSUE THREAD

**Issue by pantherale0** [JakeMartin-ICL/ha-monzo#7]
I've had the pleasure of being invited to try Monzo's under 16's account however I've noticed that this integration fails to setup now that I have a U16's account, on my account. Either that or something else is going on.

```
Logger: homeassistant.config_entries
Source: config_entries.py:604
First occurred: 16:44:38 (1 occurrences)
Last logged: 16:44:38

Error setting up entry monzo for monzo
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 604, in async_setup
    result = await component.async_setup_entry(hass, self)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/monzo/__init__.py", line 210, in async_setup_entry
    await register_webhook(None)
  File "/config/custom_components/monzo/__init__.py", line 136, in register_webhook
    webhook_register(
  File "/usr/src/homeassistant/homeassistant/components/webhook/__init__.py", line 54, in async_register
    raise ValueError("Handler is already defined!")
ValueError: Handler is already defined!
```

For info purposes if anyone is wondering, these accounts show up in HA as a new device, I believe the usual transfer services should work with this, although unable to test due to above error.

![image](https://github.com/user-attachments/assets/0b8847ad-56e0-40c9-9cbb-108992e7f731)

**Comment by JakeMartin-ICL** [comment]
Hmm, this isn't good. From an initial quick look it looks like it's because the under 16s account is producing the same webhook id, but for that to happen the account would have to have the same id too. That seems unlikely, but without testing I can't be sure. Could you go to https://developers.monzo.com/api/playground, log in, then just hit send on GET request (which I think autofills to /accounts) please? The main thing we're looking for is a duplicate `id` field. If you can't find one or aren't sure, it might be best to send the output over, but you'll likely want to redact the personal info in that case (names, `account_number`, `sort_code`, `iban` I think)

**Comment by pantherale0** [comment]
The `id` field between the two accounts are unique, in fact the U16 account contains no actual personal information apart from a record to state that I am the owner of it.

Apart from owners array:

```
id:"acc_0000AlGMeS5l95o2xr1gWn"
closed:false
created:"2024-08-23T15:40:44.091Z"
description:""
type:"uk_retail_young"
owner_type:"personal"
is_flex:false
product_type:"young"
currency:"GBP"
legal_entity:"monzo_uk"
country_code:"GB"
country_code_alpha3:"GBR"
```

And then my current account:

```
id:"acc_00009YbgA9JR0gh8JxkYbZ"
closed:false
created:"2018-07-13T14:20:42.166Z"
description:"user_00009XIZtHF9vqahKSu6dt"
type:"uk_retail"
owner_type:"personal"
is_flex:false
product_type:"standard"
currency:"GBP"
legal_entity:"monzo_uk"
country_code:"GB"
country_code_alpha3:"GBR"
```

**Comment by JakeMartin-ICL** [comment]
Strange, I'd assumed the only way this error could occur is if it tries to register a webhook with the same id (`entry_id + account["id"]`). I suppose it's also possible though that `MonzoWebhookManager.register_webhooks` is being called more than once. Are you using Nabu cloud or a local setup?

**Comment by pantherale0** [comment]
Very weird, a few reboots later and its working :/ I'm using a local setup for any oauth related configurations (although my instance is connected to nabu cloud).. I'll close for now.
