### ISSUE TITLE
Pot transfers only work for Current Account, not Joint Account

### ISSUE THREAD

**Issue by robleedotinfo** [JakeMartin-ICL/ha-monzo#8]
Seems to throw an error:

Logger: custom_components.monzo
Source: custom_components/monzo/__init__.py:107
integration: Monzo
First occurred: 20:43:24 (2 occurrences)
Last logged: 20:51:09

External error handling pot transfer: one or more transactions failed

**Comment by JakeMartin-ICL** [comment]
Thanks for reporting. I can't debug myself, but I'll try to improve the error reporting so we get a more useful message.
Ideally, I'd like pot transfers and my other improved error logging PR to get into core first, but if that drags on too long I'll get a patch on this version in the interim

**Comment by robleedotinfo** [comment]
Thanks, very happy to test further

**Comment by JakeMartin-ICL** [comment]
I've got a new version [v1.2.0-alpha](https://github.com/JakeMartin-ICL/ha-monzo/releases/tag/v1.2.0-alpha) for you that should give Monzo's API response in the logs when a pot transfer fails. . I'm keeping it alpha for now, but you can get it in HACS by redownloading and choosing the version. Let me know if it works and what you get in the logs (remove any personal data if necessary, though I'm just expecting an error), thanks

**Comment by robleeskyuk** [comment]
I've set it up, seems that in the process of changing versions I had to re-authenticate with Monzo, but once I had the transfer seems to work.  So I can't be sure, it may be the re-authenticating that made it swing into action.

**Comment by JakeMartin-ICL** [comment]
Glad it's working, I'll close this for now then. Thanks for testing
